### PR TITLE
TerminalBlock_DC_CarAudio_3pin_11_Up_HollowClamp

### PR DESCRIPTION
**Pull request by jbdwi**
Pls find .
Editing f/p : 
- moving the anchor to pad 1
- adding courtyard
  image

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Josef,

For the hollow clamp, you will want to extend the courtyard to include the protruding part. Then, please add the courtyard for the second footprint. Also, please fill in the doc and keywords in the footprint properties. I think it looks good, then!

Once you commit these small corrections to your branch, you will see your commits right here. Then, just write here that you are ready.

**Comment by jbdwi** [comment]
// quote : " Then, please add the courtyard for the second footprint."
Second footprint ? Do you mean it is the B.CrtYd ?

**Comment by jbdwi** [comment]
Hi Carl,

1)
I just guess what you meant "add courtyard for the second footprint" is B.CrtYd.
Then, I did add that b.crtyd to this fp. Pls advice if it is not correct..

2).
Also I dont know regarding "fill the doc". What doc file ? If you intend for the manufacture documents, I didnt have it since I draw it based on a real component.

3).
About keywords, again I didnt know where I have to write it.

Honestly, in this github folder structure, I feel I stand at  the " I dont know where land. " All I did here just 'by accident' or 'by luck' if it is in the correct place. 

rgds / jbd
image

**Comment by CarlPoirier** [comment]
Hi Josef,

1) You added two footprints, being PowerTerminal_CarAudio_3pin_11_Up and TerminalBlock_DC_CarAudio_3pin_11_Up_HollowClamp. The former has no courtyard.

2) How did you get the dimensions?

3) In the footprint editor, you click on the Footprint Properties icon. There, you will have one field for doc and one field for keywords.

**Comment by jbdwi** [comment]
Hi Carl,
Thanks for reviewing.

1). I have added the former with courtyard.
      - question : is it necessarily to add both side of courtyard for a thruhole devices ?

2). While I got no the datasheet , I did measure it with calliper of course. Anyway, I ll try to find the original datasheet if available in the net or at least the similar component. ( some of them have different style of the body, eventho the basic dimension always equal.

3). Ok.

**Comment by CarlPoirier** [comment]
HI Josef,

You can add the courtyard only on the side of the component. Also, ideally we need to be able to get the datasheet.

If you can fill in the doc and keywords fields as I mentionned, I will merge this pull request!

**Comment by ghost** [comment]
Hi @jbdwi 

Sorry your pull request got forgotten for so long. If you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks

**Pull request closed without merging**
