### PR TITLE
added terminal blocks from RND connect with RM 5/5.08/7.5/10/10.16mm

### PR DESCRIPTION
**Pull request by jkriege2**
datasheets:
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00023_DB_EN.pdf
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00056_DB_EN.pdf
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00067_DB_EN.pdf
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00232_DB_EN.pdf
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00247_DB_EN.pdf
http://cdn-reichelt.de/documents/datenblatt/C151/RND_205-00276_DB_EN.pdf

rnd

### CODE REVIEW

**Comment by jkriege2** [comment]
Note: These blocks were created by a small C++ programm, so changes/new versions are easily possible ... Is there any place where I can store that program too?

**Comment by jkriege2** [comment]
all footprints conform to KLC now (according to check script!)

**Comment by pointhi** [comment]
Please note the `Terminal_Block` repositories are deprecated and are likely to be removed in the future. Either place them in the corresponding `Connectors_**Manufacturer**.pretty` Repositories or contact @CarlPoirier to create a new Manufacture specific one.

As side note, for footprint generation, you can also use existing frameworks like my https://github.com/pointhi/kicad-footprint-generator which was used for most connectors inside the KiCad library instead of writing your own one. Please place your scripts in a personal repository. We don't collect them in the current state but it's good to have a reference to them.

**Comment by jkriege2** [comment]
@CarlPoirier As @pointhi suggested: could you create a library for all the RND terminal blocks? How do we do that with this PR? If you create the lib, I could fork it and add all my components.

Best,
JAN

**Comment by SchrodingersGat** [comment]
Hi Jan, still interested in this one? I could create a repo for these connectors

**Comment by jkriege2** [comment]
Yes ... I'm only thinking about redoing the script that I used to generate them (so far that was a C++-program ;-) ... maybe a Python script would be better ... But having that Repo would be great!

Best,
JAN

**Comment by SchrodingersGat** [comment]
Do RND make general purpose connectors or just terminal blocks?

**Comment by jkriege2** [comment]
I think they also make SMA, BNC, ... and other connectors:
https://www.distrelec.de/de/manufacturer/rnd-connect/man_rnc?q=*&filter_Buyable=1&filter_Manufacturer=RND+Connect&page=1&pageSize=100

Best,
JAN

**Comment by SchrodingersGat** [comment]
Hi @jkriege2 sorry this one has slipped for a while:

Following from the discussion [here](https://github.com/KiCad/Connectors.pretty/issues/83)

The (new) connector libraries should be categorized by function.

So I think I should make a new library:

* TerminalBlocks_RND.pretty

And you can resubmit these files there?

**Comment by SchrodingersGat** [comment]
Please re-submit this to https://github.com/KiCad/TerminalBlock_RND.pretty

**Comment by jkriege2** [comment]
wil do ... will just take me 1-2 weeks (I think), as I'll have to rewrite the scripts for these ...

best,
JAN

**Pull request closed without merging**
