### PR TITLE
add common PTSA terminals (originally from Phoenix contact)

### PR DESCRIPTION
**Pull request by rjmaris**

### CODE REVIEW

**Comment by ghost** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by ghost** [comment]
Hi @rjmaris 

Sorry your pull request got forgotten for so long. 

If you are still interested in contributing, please check the KiCad Library Convention errors that are reported here: https://travis-ci.org/KiCad/Connectors_Terminal_Blocks.pretty/builds/249588279?utm_source=github_status&utm_medium=notification

The latest KiCad Library Convention is here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Also, do you have a datasheet link for these terminal blocks?  When I google "PTSA terminals", I get http://uk.rs-online.com/web/p/pcb-terminal-blocks/8045593/. Is this the component you had in mind?

Many thanks

**Comment by ghost** [comment]
Closing inactive PR.

**Comment by rjmaris** [comment]
Thanks for your reply, hackscribble. My access to github has been very, very infrequent in the past year. I'll consider your remarks when I'm recalling any (also this) Kicad related stuff.

**Pull request closed without merging**
