### PR TITLE
Philmore 5mm terminal blocks

### PR DESCRIPTION
**Pull request by mignon-p**
[Philmore 5mm terminal blocks](http://www.philmore-datak.com/mc/Page%20197.pdf).  Based on `TerminalBlock_Pheonix_PT-3.5mm_2pol.kicad_mod` (basically just scaled it up, plus a few changes to be KLC-compliant).

philmore-2pol

philmore-3pol

### CODE REVIEW

**Comment by ghost** [comment]
Hi @ppelleti thank you for the contribution.

@SchrodingersGat the discussion on this other PR (https://github.com/KiCad/Connectors_Terminal_Blocks.pretty/pull/10) suggests we should not be adding to this repo. What is the best place for these Philmore terminal blocks?

**Comment by SchrodingersGat** [comment]
As it is only two footprint it's probably fine here. When the Philmore series gets large enough to warrant its own repository, we can reconsider.

**Comment by ghost** [comment]
Thanks @SchrodingersGat 

On a different point, I think the naming convention in this repo as a whole is a bit of a mixture, not in line with latest KLC.  For @ppelleti contribution, I'm going to suggest ...

`<type>_<manufacturer>_<model name>_<number of poles>x<pitch>_Straight.kicad_mod`

... which seems to be the format used in recent `Connectors_xxx` PRs.

So the names in this PR would be ...

`TerminalBlock_Philmore_TB132_02x5mm_Straight.kicad_mod`
`TerminalBlock_Philmore_TB133_03x5mm_Straight.kicad_mod`

How does that look?

**Comment by ghost** [comment]
@ppelleti I was hoping to review your contribution today, but I'm afraid I won't be able to until tomorrow.

**Comment by SchrodingersGat** [comment]
@hackscribble good suggestion - the terminal block naming convention is pretty outdated.

**Comment by evanshultz** [comment]
The `TerminalBlock...` is the only library I see without using an underscore between each word. Should it be `Terminal_Block...` or is this already the way it's intended to be?

**Comment by ghost** [comment]
@ppelleti I have a question about the drill size on the pads (1.2mm).  The datasheet says that the terminals (I assume that means pins) are 0.9 x 0.9mm.  If the pin is square and has no chamfers, that makes the diagonal 1.27mm. 

KLC 9.5 says that IPC recommended minimum drill size should be max lead diameter + 0.2mm, which would give 1.47mm in this case.

Are you able to verify this?  For example, have you used the terminal block already and know what the working drill size was?  Or any other data from the supplier about recommended drill size?

**Comment by ghost** [comment]
Other review points (they apply to both footprints) ...

#### Courtyard layer

1. Since this is a relatively large component, move the courtyard outline out so it is 0.5mm away from the body outline on the Fab layer.

#### Silk layer

2. Set line thickness to 0.12mm.

3. The three lines that represent the left, right and top sides of the terminal block need to be visible when the component is installed.  Currently they are in the same position as the Fab layer component outline.  Move the three lines on Silk outwards so they sit just outside the Fab layer outline.

4. Add a pin 1 indicator.  Suggest an L shaped line just outside the bottom left corner of body outline.  See the last example in  this image from the KLC FAQ.

image


#### Fab layer

5. Set the line thickness to 0.1mm.

6. To assist with using the Fab layer as an assembly drawing, copy your detail from the Silk layer so it appears on the Fab layer too.  I mean the horizontal lines and the small vertical line that show which side the wire entry is on.  Keep them on Silk layer as well.

image

7. Copy the pin 1 indicator so it is on Fab and Silk in the same position.

#### Properties

8. Add the datasheet URL to the end of the current description.

9. When we have resolved the question about footprint name, the 3D model details will need to be updated to match.

@SchrodingersGat Couple of questions:
- Do you have a view on @evanshultz comment above on name format? 
- The 3D model folder in `kicad-library` is called `Terminal_Blocks.3dshapes` so does not match this repo. What should we put in the 3D reference in these footprints?

**Comment by mignon-p** [comment]
> KLC 9.5 says that IPC recommended minimum drill size should be max lead diameter + 0.2mm, which would give 1.47mm in this case.

Sorry, I had neglected to update this from the original `TerminalBlock_Pheonix_PT-3.5mm_2pol`.  I have corrected the diameter to be 1.47mm.

> Are you able to verify this? For example, have you used the terminal block already and know what the working drill size was? Or any other data from the supplier about recommended drill size?

I measured a pin with my calipers, and it appeared to be 0.82 x 0.92 mm, which seems close enough to 0.9 x 0.9 mm.

I have not yet used the terminal block on a board, although I plan to do so soon.

I do not have additional data from the supplier.

> Other review points (they apply to both footprints) ...

Thanks for the detailed feedback!  I believe I have corrected all of these issues in my latest commit.

> When we have resolved the question about footprint name, the 3D model details will need to be updated to match.

I have gone ahead and updated the names to `TerminalBlock_Philmore_TB132_02x5mm_Straight` and `TerminalBlock_Philmore_TB133_03x5mm_Straight` for now.

**Comment by ghost** [comment]
Posting updated images for reference.

image
image

**Comment by ghost** [comment]
Thanks @ppelleti the changes look good.  I will allow a couple of days to see if we get answers on the name and 3D path questions.  If not, I will merge anyway and we can sort it out later if required.

**Comment by ghost** [comment]
Thanks for your contribution.

**Pull request merged**
